---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-admin-credentials
  namespace: jenkins
spec:
  encryptedData:
    admin-password: AgAsEYmc7ovbWgzAbcb7O6cmAqDauwrzWUfL9dx9Gcl/zPmL6oMnPVKR4Fzi8np332vqgwinhqnTBTPp5EFQ28mQvVrOhySUch4a5bjQcpFUnfRns0bf63Lt9ywUmL4h5BfP/PQby0d47nxtEqyxLQ2u868XDQmM1x2UO3YsaSOExw8ptrF+67mOK3VpOssP/pqUiScsTmwDe0u7HezEBeaZtNlARESUf8qR/ytZQLBjJoRfA7HWu2thuFW/tC14H2Iko9OIhLYo3iwMGAc8SapbbS3LhzbVZKySpWwADrYBvSpuqQHogTHcsSP4Ty50YbOzBsS2cB5FWvJv/asGJ5A6zob7/mBfDSQ2Za188D25sVm+LkBezojJlni6b/0PffOkYbbOg1FpcbH0rxEXhMWkoD0VwU7TT1trfX94vJbYWeYH2awztBY8IpjQA04nyhPa0q35mkKEspQcdvOATPuvGTTQC2Q5yTMOlUPlmSOEEfWjACCuouxTUtWxo5KKgSRwBrVrFGYz2djc8cw3m9QL0cgaX6LMuh7ub5NFFlblwZ6BAr1WiwMV7w3pO0r174OJpgYCxaF+Dk9UH7havoExzDd6VIkKHrdDRG8T1LsZVZkpu67KFBLdOkuRigxeQi1oLJaQevk7bGmaOwiz1F8mgA5HmTPiWjSLA5rpqE+SS0FkzEJiVHJm+gqy+/FKLhqbmPj8b/gA3dc=
    admin-user: AgArZ8stRVTErisagzeuEVxLXW0SACrPKdfHZ7iwzOiyhKukIK6EZkm9pONDV6BZ7cYs+NcIG/rn+zSIbNXpuEFeHx638vn+JaSMz+gamMxjnRFNlzbq+n+tjcXy2dPi9WFNsEERaXCzRxttJslyhRs+8IAXtS5A31MaX+jSdipK3EHoqOlAivh0OlB+cO9WR5ehGMkgKIIiR9ggxFUkNnV35/G013ycLIScohPX3r+KGFbf8kETd1usG1pS89k/SvL2MBMk13HRMzRM+faCBAbERL5CcU/KwdmZ7IpeTnzQ1nQSHE3n50PQdAULMYHBdM2VDm76c2WiofnvYEkdbSQ26UbDcO+1k0YF6tHETGMpFuJsmZw+lfRw95Jc8gQAQI+BOVduapR39RsV8E15i2+cj43Z4JJ2IqJ4qgUxR32ROgwEUz0YvM+qN14PBv1WuovdQyURd3HR64It0RvllRjKUyyyzCTIslools6dPZeGQevhR50dp3FN4dK0BxL+s2T/XrXZR688cCzHsakQ1US08yxJIFrnGretFvppqD4J2Stt76b1LyW/C9k1f7TVDqrgcPuboVq+OU7tZP/JkHeyjJYJj/p4huh461e7grdThNkY0KginTQaFTBzYgKEJetQNvP8xPWryhAVUEGQX8+I/mWB92Twoe6eYVVeJStDBNwGc6Co/n9F+ySaXIgXUTaZx86mjg==
  template:
    metadata:
      name: jenkins-admin-credentials
      namespace: jenkins
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCrF6Uk+ZcRAKrRMq4/SV0RYAI34hWaL4JyZFYp4CTqoGqT3SRIkFLb5gBea2wyoif/EgoZmWYu6WIT8ulGbLFsXEmm1H5145Nzvsk5F/LAnbBFr8K88xn0UmsFmvXJZ+4YUt8hFw3H9rw/L0vippMXIP7dNtxhnaS2rdEVFKTHjLWDo4P5Gd1MAX9Fdj9BNjlmo8jVBZjjWJjT5xd1LBslMqB7sc3Np3RQyrWDWBpHZB4+U6BeEQP7Bb39d92+29b90hmbFSa0cocMWoIvEXlOCuh7Z7ec7Z+kH3uxNR8cWu2dkEEGFekhGM3EN8px1jhrjPtnXE0n0lGzLmoXRGac877BkJ2pCb+NOoY3r6JDdWuO/7qs8avZl04NKj4fKy0XoFRPXrCAdpcuFSsuPgdfVF0wnW7EmYfUoP/AEBwuUuu+J2M9X0NtnK90G1Lh3qyD6LLSXjHdfpmOsiBp/U1lJxyRw3ojdR7aZT90s3LL+GOuWrfgkZ7IGuIlIR9dA9tZMz7OkvKUJ1OYcuP44q+4BIwgC6T1wufQwRrDF35IQzNCthlalQA2A0z/TfGAvnyoLL72Tzp/cZ7eTHo0/LqbI2uc1crGXFmvuJVVwD6nGHU7NnMImuNG/l10It2+Jd994yus2Ssrf67RytLAw39eBC2wv+167qG3EPX/e1JSy/WLxm0sxzpB1UNCt7favIQyj20ii2+H3hY=
    admin-user: AgCq2DLtQqc723XYApAyxZiAVlTl6YcX1trdXt5x9KrjwGDDqii0y/f+e6zcDo9mMpnfH3m0LNsiVdrXEaUT/w9W0BGFol6ID0AziGqwxSDr/qGDeZ8daKgaM24ahitQFHj/5HryeEzUhG7+lrg4jaWNZJOZjlvmkhTMog16EW/qCkDFJgCYTAojeM0ECttG2ANf1JKsned34MWhuZ8L5RwBDgbsOZRKMfPRUUzcLZ5M3BfeHcLEAC82Gm6i7zZRDIe4aVstLs1Y0ZHsFhmxj/lfI4f0HDjNBzz6/qDn5NMemyGfhPcOOdt/uA1E5pN1QzeLWsCxZyjkA4G9xnpUsQRH33rDDzq4RMZoBsAi8Mi0pdEhWsNqFGcqZzr1FP1W1HY20qUiuDlVaf/UaXYVJCXfBJLYUYJNvFjeBYsUTTAyyxcbvPdctgP4pObPSg7+07o8B4dB2h21hRelygMEmNukd9sge2qrYXCZvSvsFoyXSp4e56FHprtgCpjSOHtKXi7pzKKmEKQENyjPqLdewYz8jRASJMkhZX9niK3+yWZlFmTbMHNUEsTxwU+wRGlKiMMWprZSH0Ceo3inK6y35UvqjtVt18iKzAHntm+7/knKIpbJ2ssishwTeqqq68VrRCAzOkz+BvQG/+zmwsm8bgj0lRniTwIg0KGV7dDx0QGCjXB1DYRnSSQWPDynuYc7AkdmWBThMw==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: elasticsearch-credentials
  namespace: logging
spec:
  encryptedData:
    admin-password: AgBSDWK2zoVWEil80iOtiuqNDtPDk3ScxDHaBGr9mIDNcoAY6ylN12gpqwzk7OPZUmQcI5lSkBKF0O5BMmp3HcdAQ3I36u+efC5I7lwAQLsS2mcVLKtQ+15wK7Xjs2gj6gVZrI+aI6O1tIkCghnugjTnW35ycxw3co54AG7+35MIQ6y/koGS6aS3gNcOmNECzSdV0G+H+P3H2/EAGvcMGLZ4dYknb/YhTSWZzyKPzSb3PgQ18Diiyp16xTDzpnO0bhB/m+OWwXvbslbWcZgoqBgR4+gW7zgQUib4WkSR15g7x5UwpeJkRXYIcSxUqFsK1qODkVpc6P05H5oEvLwrx3smw/UDZ9JJbw9DrtanlHEYvZf9ACqX24k+ciUJIwiPTW8hAc/RgO8vJUWG0rvzyPFA/LaYspwK+T+x+2lCx+fonTVrq+/GbZ9qE2AnWlxSRkHQSRsgexToLtXqsMXkeuiEl4AD1WKcro9ZXlTHjbuBMrVAN6gXQzHkfjZ4weHZlvyc3fF0m7e7NtLy3uDaZS1TV0zcJ34JJ2wSg9V5LUOI+0qSthF87daMwbY5bF3Njo17eZwiBZx6C5mFU58ptBE752I941wFNPI1+rGkfiBefsN2LNVU+nKEZWOslfISr6BVj3Ub/JqDwwCOGZwZYqPkvH8ThBswCTUl45qKgkgtPBgjhELSy6qsXytQVrMQmKy3Z5Lu6PqhTpQ=
    admin-user: AgAKgj/NNsqn7Kyo/7avLJZFmUQVLq6FMIGsbv8/0CUEpDrti3mQMUC9Kcn3WvwuMY0Z2rvZ4SPPjxIf9BhrL+AF6l+Y3AHX5WSYGJ0gnOCcF8NDMtZSor2Jw2R9SEnZnz4qsWT1iss4efYcXrcILUV3jv52WMlzghs/1ElaHZGTgJUxyRR6YnE9HYsk5P1SDV5Sa4tReuvDP9PUsBBLBpCl4YvtK9ct1SgEo9inM1Z0VDYguIMfLwEcVWzwlTrJirCdqaJTriOZNHHqKqiKlhhJP7Wyh6ZnnjcB3lJnrvsqsEhWc+of6w1A1CNB/u/QDmf4X5Cgwmyagjm2fGOCPclIFgvkXtZoCkM2vaFCGTaMnYh1gX3oLxOUIOljFOapRUJ8ezTGy78+N5BvO3WQi/Bx4iSyK97B3IYMzH0ofCceY+veqrpp+Zk8RGcXOjlWWFwQ04PYemLAMKQyu0hy2e0gzHWwld78kC2r//WIeK0YQHoZ1McRoXxGDUMXzF4Rq1+syDvM/ft23HdMols8JunobwsdYRJ5OoL5JbhNWZb1Fo60Jo1OxTYTvMzjQxDtIIf/FjB0zxtH14pPQfa6c5XAswuaurfd/BDsyEJHZHn59dcNJ4I//dksM0uaNY/FCrinuLA7MjW1Fe8QXJsWhvHfc+D42OG8AscgBcPr4tcQV22Bl7uFfQ9pJJo5q/0qzdHh20U7jqh2
  template:
    metadata:
      name: elasticsearch-credentials
      namespace: logging
    type: Opaque
