apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.43.0
    chart: fluent-bit
    helm:
      valuesObject:
        config:
          outputs: |
            [OUTPUT]
                Name            es
                Match           *
                Host            elasticsearch-master.logging.svc.cluster.local
                Port            9200
                Logstash_Format On
                Replace_Dots    On
                Retry_Limit     False
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
