apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    targetRevision: 5.9.32
    chart: jenkins
    helm:
      valuesObject:
        controller:
          admin:
            existingSecret: jenkins-admin-credentials
            userKey: admin-user
            passwordKey: admin-password
          nodeSelector:
            dedicated: jenkins
          serviceType: LoadBalancer

          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi

          javaOpts: "-Xms512m -Xmx1g -XX:+UseG1GC"

          JCasC:
            defaultConfig: true
            configScripts:
              welcome-message: |
                jenkins:
                  systemMessage: "Welcome to our GitOps managed Jenkins."
        persistence:
          enabled: true
          size: 8Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
